# Generated by Django 4.1.3 on 2022-11-07 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='details',
            field=models.TextField(default='-', max_length=3000, verbose_name='Содержание'),
        ),
    ]
