# Generated by Django 4.1.3 on 2022-11-10 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_task_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='details',
            field=models.TextField(blank=True, default='-', max_length=3000, null=True, verbose_name='Содержание'),
        ),
    ]
